### ISSUE TITLE
Задокументировать класс Track

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/yandex-music-api#103]
Необходимо полностью задокументировать класс [Track](https://github.com/MarshalX/yandex-music-api/tree/master/yandex_music/track/track.py). Пример правильно задокументированного класса: [cover.py](https://github.com/MarshalX/yandex-music-api/blob/master/yandex_music/cover.py). Спасибо за Ваш вклад!

**Comment by eugenweissbart** [comment]
Взялся

**Comment by MarshalX** [comment]
@eugenweissbart  как успехи?

**Comment by eugenweissbart** [comment]
Впадал в кому из-за дедлайнов на работе, постараюсь в ближайшие дни добить.

**Comment by Angel777d** [comment]
Взялся
