### ISSUE TITLE
Баг с лайканием объектов (трек, альбом, артист, плейлист) через клиента

### ISSUE THREAD

**Issue by n1EzeR** [MarshalX/yandex-music-api#107]
Метод `client._like_action(object_type, ids, remove=False, user_id=None, timeout=None, *args, **kwargs)`

Методы `client.users_likes_*object*_add()` вызывают метод `_like_action` пропуская параметр remove.  Пример: `client._like_action('artist', artist_ids, user_id, timeout, *args, **kwargs)`. 

Интерпретатор не понимает, что параметр remove был пропущен и передает ему значения переменной `user_id`. Его можно было бы пропускать, если бы мы, например, передавали значения в формате `user_id=11122` и `timeout=None`.

Проблема ранее не выявлялась так как `_like_action` принимает для `user_id` значение параметра `timeout`, который был равен `None`, а следовательно значение `user_id` присваивалось `self.account.uid`

**Comment by n1EzeR** [comment]
Pull request с исправлением вышлю в ближайшее время (час-два)

**Comment by n1EzeR** [comment]
Pull request - https://github.com/MarshalX/yandex-music-api/pull/108

**Comment by MarshalX** [comment]
Большое спасибо. Надеюсь, этот ПР засчитается Вам в Hacktoberfest!
