### ISSUE TITLE
Отсутствие метода with-tracks у albums

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/yandex-music-api#11]
Пример URL'a: `https://api.music.yandex.net/albums/3663639/with-tracks`
Пример JSON ответа: https://codepaste.ml/074c6829/

**Comment by panczeslaw** [comment]
Есть подвох в volumes. Внутри листа могут быть несколько листов из треков. Используется для группировки треков внутри альбома. Нигде нет информации о том, зачем эти разделы, ну кроме как в примере.
Альбом: https://music.yandex.by/album/625175
Ответ на него: https://api.music.yandex.net/albums/625175/with-tracks

**Comment by MarshalX** [comment]
> Есть подвох в volumes. Внутри листа могут быть несколько листов из треков.

Не вижу никаких проблем для реализации. Даже если группа одна - вернётся список из одного элемента. 

> Используется для группировки треков внутри альбома. Нигде нет информации о том, зачем эти разделы, ну кроме как в примере.

Вы говорите, что непонятно зачем эти разделы, но даёте пример где разделом является "Диск". 

Кстати, стоит обратить внимание на следующее:

contentWarning | "explicit"
-- | --

Может это послужило разбитием. Правда на сайте предупреждей никаких нет.
