### ISSUE TITLE
Свойство tracks в Playlist содержит list, а не TracksList

### ISSUE THREAD

**Issue by gleb-liutsko** [MarshalX/yandex-music-api#117]
Свойство `tracks` класса `Playlist` содержит `list`, хотя логичнее и удобнее было бы, наверное, если бы оно содержало объект класса `TracksList`
https://github.com/MarshalX/yandex-music-api/blob/22a1997b513a6e39bba77c0f1d140b9f56c51173/yandex_music/playlist/playlist.py#L135

**Comment by MarshalX** [comment]
Прошу прощения за долгий ответ. Данное решение считаю в корне не верным, потому что никогда не видел в ответе от API (связанным с плейлистами) объекта `TracksList`. Только что это перепроверил. Помимо этого заметил, что они окончательно убрали список треков при возвращении плейлиста в списках. Это касается как получения плейлистов по ид (`users_playlists_list`), так и `langing`'a. Раньше (месяца два назад) треки возвращались в `users_playlists_list`, а в `langing` их short версия. Сейчас же нет вообще ничего. Единственным способом получения треков у плейлиста остался эндпоинт `/users/{UID}/playlists/{PID} `. Данный эндпоинт отдает полные версии треков (класс `Track`).

Удивительно, но я не нашел его реализации в коде. Так же метод `users_playlists_list` является дубликатом метода `playlists_list`. За исправление этого возьмусь прямо сейчас.

Жду Ваших комментариев по поводу наличия `TracksList` объекта в ответе API с плейлистом(ами). Прошу заметить, что библиотека полностью повторяет их реализацию и не бориться со странностями, багами и нелогичными вещами.

Спасибо за работу!

**Comment by MarshalX** [comment]
Доразобрался в вопросе. На эндпоинте `/users/{UID}/playlists/{PID}`, который на данный момент не используется в библиотеке, возвращается список полных треков внутри объекта, который ранее не встречался.

Сейчас использутеся /users/{user_id}/playlists с POST параметром kinds, но там в том же поле `tracks` возвращается обычный list состоящий из `TrackShort` объектов.
