### ISSUE TITLE
Неразбериха с ID треков

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/yandex-music-api#12]
Какой-то герой когда-нибудь разберется где какой ID использовать. Просто `track.id` или `track.id + ":" + track.album_id`

Была идея отойти от их API и создать собственный класс ID поддерживающие разные варианты. TODO тут: https://github.com/MarshalX/yandex-music-api/blob/master/yandex_music/utils/difference.py#L39

**Comment by panczeslaw** [comment]
Второй вариант, так как album_id всегда есть возможность подтянуть. И неважно какой, из нескольких вариантов можно рандомный подавать. По крайней мере веб версия Я.Музыки перекидывает к какому-то альбому, по ссылкам типа https://music.yandex.ru/track/46262532

**Comment by MarshalX** [comment]
> И неважно какой, из нескольких вариантов можно рандомный подавать.

Мне кажется, в Яндексе так же кто-то предложил. Посмотрите баг №2 в статье на [habr.com](https://habr.com/ru/post/462607/) об их API.

**Comment by MarshalX** [comment]
При наличии альбома (должен быть вседа, хотя бы один) используем `track_id:album_id`, иначе `track_id` (легаси кейс). Собственно так и работают проперти `track_id` в библиотеке, которые и нужно использовать
