### ISSUE TITLE
Добавить типы в сигнатуры методов

### ISSUE THREAD

**Issue by Yanpas** [MarshalX/yandex-music-api#120]
Пользуюсь vscode, аннотации типов пригодились бы для автокомплита.

**Comment by MarshalX** [comment]
Не знаю как анализатор VS обрабатывает хинты полей класса. Может ли он из аргументов констуктора подгребать типы? 

Пути два. Или явно указать каждому полю тип после обьявления класса, либо только в конструкторе.

```
class Foo:
    bar: str

    def __init__(self, bar: str) -> None:
        self.bar = bar
```

Как делать будем? Мне кажется, что указывать еще отдельно полям тип это оверхэд

**Comment by Yanpas** [comment]
Да, из типов аргументов конструктора типы извлекаются.
```python
class A:
    def __init__(self, foo: str):
        self.foo = foo

A(555).foo # foo показывается как str 
```

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api/tree/issue-120

В общем что смог, то сделал. Местами не хватает, но очень редко и в таких кейсах, где особо и не надо. Огромный процент имеет тайп хинты. Теперь должно быть гораздо приятнее деволопить.

Желательно подёргать методы Client'a с Python'a 3.6

**Comment by Yanpas** [comment]
Спасибо большое!
