### ISSUE TITLE
Инициализация Client без авторизации

### ISSUE THREAD

**Issue by panczeslaw** [MarshalX/yandex-music-api#14]
Всё будет работать даже без авторизации. Вроде как достаточно обернуть инициализацию Client [здесь](https://github.com/MarshalX/yandex-music-api/blob/b0236fd3bf22ae17b02c4ec92b4806b8c0ec1045/yandex_music/client.py#L63) и добавить обработку исключений где идёт обращение к `self.account`.

**Comment by MarshalX** [comment]
Добавлено. Осталось только примеры в README поправить.

**Comment by MarshalX** [comment]
И псевдоним создать
