### ISSUE TITLE
Handler-функция для обработки капчи

### ISSUE THREAD

**Issue by gleb-liutsko** [MarshalX/yandex-music-api#140]
После нескольких неудачных попыток входа, Яндекс просит ввести капчу. Нужно добавить возможность обработки при помощи handler-функции.

**Comment by gleb-liutsko** [comment]
Разгадал как происходит обработка капчи в приложении для Android.
[Пример реализации](https://gist.github.com/gleb-liutsko/b62550a9df2c3b79d54fa1bb451cb77e)

Когда сервер возвращает ошибку "Wrong CAPTCHA answer", он в свой ответ добавляет два дополнительных поля:
-  `x_captcha_url` содержит url капчи.
- `x_captcha_key` уникальный ключ капчи

Для того, что бы отправить ответ, нужно при следующей попытки авторизации отправить дополнительно два поля:
- `x_captcha_answer` разгадка капчи
-  `x_captcha_key` уникальный ключ капчи

Т.е данные в запросе будут иметь следующий вид:
```python
{
	'grant_type': 'password',
	'username': 'qwe',
	'password': '123',
	'client_id': '23cabbbdc6cd418abb4b39c32c41195d',
	'client_secret': '53bc75238f0c4d08a118e51fe9203300',
	
	'x_captcha_answer': '932811',
	'x_captcha_key': '002v3BYku1P3SNlobj3nV8Y4emt4Zr3S'
}
```
Если капча разгадана неправильно, то возвращается ошибка "Wrong CAPTCHA answer" и новые поля `x_captcha_answer`, `x_captcha_key`

**Comment by MarshalX** [comment]
@gleb-liutsko, большое спасибо! А сервер возвращает просто два дополнительных поля или отвечает 403-ей (при попытке авторизации с ответом на капчу)? Посмотрите мой коммит для этой таски. Там новый объект для ответа сервера, если нужна капча.

**Comment by gleb-liutsko** [comment]
Возвращает дополнительные поля и также отправляет 403-й код
