### ISSUE TITLE
Все альбомы исполнителя

### ISSUE THREAD

**Issue by gleb-liutsko** [MarshalX/yandex-music-api#141]
Сейчас, в библиотеке не существует способа получения всех альбомов исполнителя. Можно получить только список главных альбомов (без синглов и тп).
Нужно в класс `Client` добавить метод для получения всех альбомов исполнителя. Для этого можно использовать эндпоинт `/artists/{Id_artist}/direct-albums?sort-by=year&page={page}&page-size={size_page}`

**Comment by MarshalX** [comment]
Разве `Client.artists_brief_info` не вернёт в `albums` поле все альбомы? Я конечно вижу, что тут и сорт по году есть, и пагинация, но я с начала разработки библиотеки не добавляю методов, которые повторяют функционал других, делая это чутка иначе. А таких тут достаточно

**Comment by gleb-liutsko** [comment]
> Разве `Client.artists_brief_info` не вернёт в `albums` поле все альбомы? 

Нет, не вернет. В этом свойстве содержится укороченный список альбомов, которые могут попасть на главную страницу артиста.

Вот несколько примеров:
### [Eminem](https://music.yandex.ru/artist/1053)
![EminemWeb](https://user-images.githubusercontent.com/40576167/69156731-4b076180-0afd-11ea-89d0-af3528c2e6c9.jpg)
![EminemCMD](https://user-images.githubusercontent.com/40576167/69156733-4b9ff800-0afd-11ea-9284-0b338eea892e.jpg)

---

### [Noize MC](https://music.yandex.ru/artist/160970)
![NoizeCMD](https://user-images.githubusercontent.com/40576167/69156926-9e79af80-0afd-11ea-9353-131c80b469a6.jpg)
![NoizeWeb](https://user-images.githubusercontent.com/40576167/69156927-9e79af80-0afd-11ea-8d51-b0e2397f890b.jpg)
