### ISSUE TITLE
Ошибка авторизации с использованием прокси

### ISSUE THREAD

**Issue by makar47** [MarshalX/yandex-music-api#159]
Невозможно авторизироваться по логину/паролю с использованием socks5:

```
request = Request(proxy_url='socks5h://127.0.0.1:9050')
client = Client(request=request).from_credentials('Login', 'Password')

```
Ошибка:

> yandex_music.exceptions.NetworkError: HTTPSConnectionPool(host='api.music.yandex.net', port=443): Max retries exceeded with url: /account/status (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f006249a050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

Выход из ситуации: получать токен принудительно:
```
token = Client(request=request).generate_token_by_username_and_password('Login', 'Password')
client = Client(token, request=request)
```

**Comment by MarshalX** [comment]
Теперь вот так должно работать корректно 
```
request = Request(proxy_url='socks5://user:password@host:port')
client = Client.from_credentials(os.environ.get('LOGIN'), os.environ.get('PASSWORD'), request=request)
```
