### ISSUE TITLE
Плейлист с Алисой

### ISSUE THREAD

**Issue by glebliutsko** [MarshalX/yandex-music-api#185]
Сейчас в библиотеке нет способа получения коментариев Алисы. Не помешало бы реализовать это в бибилиотеке.

Для получения кометария Aлисы используется следующий эндпоинт: `https://api.music.yandex.net/after-track?from=mobile-landing-origin-default&prevTrackId=46624176:6294933&nextTrackId=16514776:1925140&context=playlist&contextItem=940441070:686952&types=ad&types=shot`.

В ответ приходит вот такой объект:
```json
"shotEvent": {
    "eventId": "5e25fb2c0cf28e741cb996eb",
    "shots": [
        {
            "order": 0,
            "played": false,
            "shotData": {
                "coverUri": "avatars.mds.yandex.net/get-music-misc/49997/img.5da435f1da39b871a74270e2/%%",
                "mdsUrl": "https://storage.mds.yandex.net/get-music/1634376/public/shots/1036797_1574621686",
                "shotText": "Бард - это не просто певец, это поющий поэт.",
                "shotType": {
                    "id": "alice",
                    "title": "Шот от Алисы"
                }
            },
            "shotId": "1036797",
            "status": "ready"
        }
    ]
}
```

**Comment by MarshalX** [comment]
@glebliutsko Спасибо. А получение самого плейлиста?

**Comment by glebliutsko** [comment]
@MarshalX Точно так же как и "Плейлист Дня"

**Comment by MarshalX** [comment]
Пример протух. Так же смущает `&types=ad&types=shot`

**Comment by MarshalX** [comment]
Не смог воспроизвести. Объекты воссозданы по примеру. Не ясно что есть `contextItem`. По идеи это должно указывать на плейлист, так как `context=playlist`, однако я не пойму откуда там второй ID через двоеточие. Так задаются только треки, но такого трека не существует. 

Более того, этот эндпоинт и правда (скорее всего) умеет возвращать рекламу для воспроизведения.

Осталось разобраться с отправкой запроса и всеми параметрами, исправить доку, написать тесты к новым классам, добавить download методы для обложки и озвученного Алисой шота.

**Comment by glebliutsko** [comment]
Параметры:
1. `prevTrackId`- предположительно, трек игравший до этого. Точно сказать не могу из-за отсутствия тел. на Android. На получения "Шота от Алисы" не обязателен, можно не отправлять, но возможно нужен для рекламы.
2. `nextTrackId` - следующий трек, для него и возвращается "Шот от Алисы".
3. `context` - объект откуда играет трек (альбом, плейлист и тд). В случие с Алисой равен `playlist` .
4. `contextItem` - ID объекта откуда играет трек. Для плейлиста равана `{user_id}:{playlist_id}`. Плейлист с Алисой пренадлежит пользователю c ID `940441070`.
5. `types` - тип получаемого значения. Получить рекаламу у меня так и не получитось. Скорей всего из-за подписки.
6. `from` - без понятия.

---

Для получения шота нужна авторизация
