### ISSUE TITLE
Изменение и получение настроек пользователя

### ISSUE THREAD

**Issue by glebliutsko** [MarshalX/yandex-music-api#195]
Сейчас в библиотеке нет возможности изменять настройки пользователя.

Для изменения настроек используется эндпоинт `/account/settings?{param}={new_value}`. В ответ приходят новые настройки.

Для получения настроек есть 2 эндпоинта:
1. `/account/settings` без GET параметров
2. `/users/{user}/settings`. В этом случаи  можно получать чужие настройки

Ответ во всех 3 эндпоинтов одинаковый
```json
{
   "invocationInfo":{
      "hostname":"music-stable-back-man-11.man.yp-c.yandex.net",
      "req-id":"1579809253475852-14755622876646156459",
      "exec-duration-millis":"1"
   },
   "result":{
      "userSettings":{
         "uid":410060648,
         "lastFmScrobblingEnabled":false,
         "shuffleEnabled":false,
         "volumePercents":75,
         "modified":"2020-01-23T19:50:57+00:00",
         "facebookScrobblingEnabled":false,
         "addNewTrackOnPlaylistTop":false,
         "diskEnabled":false,
         "showDiskTracksInLibrary":false,
         "userMusicVisibility":"public",
         "userSocialVisibility":"public",
         "rbtDisabled":true,
         "theme":"black",
         "promosDisabled":false,
         "autoPlayRadio":false
      }
   }
}
```

**Comment by MarshalX** [comment]
> Для изменения настроек используется эндпоинт `/account/settings?{param}={new_value}`. В ответ приходят новые настройки.

Как-то с первого раза не заработало.

> Ответ во всех 3 эндпоинтов одинаковый

Ответы своих настроек и настроек другого пользователя слегла отличаются вложенностью, например

**Comment by MarshalX** [comment]
> Как-то с первого раза не заработало.

Обязательно нужно отправлять POST, а параметры пихать как угодно, хоть в тело, хоть в урл
