### ISSUE TITLE
[Вопрос] Если примеров еще нет, то где endpoint?

### ISSUE THREAD

**Issue by DanGSun** [MarshalX/yandex-music-api#2]
Что я должен сделать, чтобы получить ссылку на трек по его ID?

**Comment by MarshalX** [comment]
Уточните пожалуйста. Речь идет о прямой ссылки для загрузки трека?

**Comment by DanGSun** [comment]
@MarshalX, да, о прямой загрузке трека. Сейчас посмотрю примеры.

**Comment by MarshalX** [comment]
Разобрались?

**Comment by DanGSun** [comment]
Да, спасибо.-- -----------------------------------------С уважением, Даниил Горлов,лидер SolarFind Inc.,E-Mail:president@solarfind.netDanGSun@yandex.ruСоциальные сети:vk.com/DanGSun------------------------------------------Sincerely, Daniil Gorlov,the CEO of SolarFind Inc.E-Mail:president@solarfind.netDanGSun@yandex.ruSocial networks:vk.com/DanGSun19.07.2019, 11:21, "MarshalX" <notifications@github.com>:Разобрались?

**Comment by DanGSun** [comment]
Да, спасибо
