### ISSUE TITLE
Поддержка Я.Радио

### ISSUE THREAD

**Issue by DanGSun** [MarshalX/yandex-music-api#20]
Возможно ли сделать интерфейс, для получения и обновления списка треков какого-либо радио? Или же получения трека, который надо играть в данный момент?

**Comment by MarshalX** [comment]
[Вот](https://github.com/MarshalX/yandex-music-api/tree/master/yandex_music/rotor) большинство классов необходимых для работы с радио. Так же у `Client'a` есть следующие методы связанные с этим: `rotor_account_status, rotor_stations_dashboard, rotor_stations_list, rotor_station_genre_feedback, rotor_station_genre_feedback_radio_started, rotor_station_genre_feedback_track_started, rotor_station_genre_info, rotor_station_genre_tracks`.

Признатья честно, когда я это писал - сам не смог ответить себе на вопрос "а как получить следующие треки?" Ибо API выдает первые 5 что ль, не помню уже. В любом случае на тот момент у меня в приоритете были другие задачи и к изучению радио я так и не вернулся. Поэтому на данный момент возможности что Вам надо нет. 

Если Вы разберетесь и опишите процесс - буду благодарен.

**Comment by DanGSun** [comment]
Когда я пытался решить эту проблему без вашей библиотеки (еще до момента ее создания), там был какой-то параметр в запросе списка треков, который говорил, что за трек я слушаю сейчас, и отталкиваясь от этого Я.Радио выдавало каждый раз новые треки. Сейчас уже не вспомню, что за параметр.

**Comment by DanGSun** [comment]
Многовато issue. так и потерять старые можно...
