### ISSUE TITLE
Не безопасно!

### ISSUE THREAD

**Issue by Metisav** [MarshalX/yandex-music-api#23]
https://github.com/MarshalX/yandex-music-api/blob/1a6d82922e5a03a7ea6890da5ec67437d76a2a44/yandex_music/client.py#L12

не хорошо так хранить, мало ли забыли

**Comment by MarshalX** [comment]
[README - Доступ к вашим данным на Яндексе](https://github.com/MarshalX/yandex-music-api#id3)

**Comment by Metisav** [comment]
Опять моя невнимательность, прошу прощения
