### ISSUE TITLE
`client.users_playlists_list()` Не перечисляет все пользовательские плейлисты

### ISSUE THREAD

**Issue by NuarkNoir** [MarshalX/yandex-music-api#233]
**Опишите ошибку**
При вызове `client.users_playlists_list()` возвращаются не все плейлисты пользователя.

**Воспроизведение**
Шаги для воспроизведения бага:
1. Создать клиент и авторизоваться
2. Вызвать метод клиента `users_playlists_list()`
3. Возвращённый список будет содержать не все плейлисты пользователя.

**Ожидаемое поведение**
Все плейлисты из раздела "Плейлисты" должны быть возвращены.

**Логи**
```python3
from pprint import pprint
from yandex_music import Client


client = Client.from_credentials(LOGIN, PASSWORD)
plists = client.users_playlists_list()
pprint(plists)
# >>> [{..., 'kind': 1003, 'title': 'Test playlist', ...},
#      {..., 'kind': 102, 'title': 'Распознано', ...},
#      {..., 'kind': 777, 'title': 'Понравилось на Радио', ...}]
# Отсутствует {'owner': {...}, 'cover': {...}, ..., 'kind': 3, 'title': 'Мне нравится', ...}
```

**Дополнительная информация**
В частности - плейлист "Мне нравится". Может быть какие-то другие ещё, лично у меня плейлистов не много и этот - единственный отсутствующий. Тем не менее, его можно получить с помощью `client.users_playlists(kind=3)`

**Comment by MarshalX** [comment]
@NuarkNoir Плейлист "мне нравится" является уникальный плейлистом, не таким как все. Он присутствует у всех пользователей, его нельзя удалить, его нельзя скрыть и т.д. Для получения треков из этого плейлиста существует отдельный метод у Client'a. То, что этот плейлист не возвращается среди плейлистов пользователя - нормально. Вы правильно подметили, что этот плейлист всегда и у всех с ID = 3. Так можно получать этот плейлист, да, но с некоторыми особенностями. Например, обложка такого плейлиста будет обложкой последнего лайкнутого трека, а не привычная нам иконка.

**Comment by NuarkNoir** [comment]
@MarshalX т.е. можно закрывать issue?

**Comment by MarshalX** [comment]
@NuarkNoir Отсутствие плейлиста "мне нравится" среди возвращённых плейлистов методом users_playlists_list() не является багом. Можно закрывать)
