### ISSUE TITLE
Сохранение сессии пользователя

### ISSUE THREAD

**Issue by NuarkNoir** [MarshalX/yandex-music-api#234]
Feature-request: сохранение сессии пользователя в файл, как это сделано в [python273/vk_api](https://github.com/python273/vk_api)

Яндекс реагирует на каждую авторизацию, думаю, это может привести к заморозке аккаунта (мало ли, какие у них там боты сидят и проверяют активность пользователей).

**Comment by MarshalX** [comment]
@NuarkNoir Реализация данной фичи переложена на разработчиков, использующих библиотеку. Для этого есть метод авторизации по токену и по кредам. Хранение токена у всех разное. У меня вот в базе, а не в файле. Каждый разработчик делает это по-своему. 

То, что вы просите сделать в библиотеке, занимает строк 5 максимум, с обработкой "протухшего" токена у вас в коде единожды. ✨

**Comment by NuarkNoir** [comment]
> Хранение токена у всех разное

Справедливое замечание
