### ISSUE TITLE
ProxyError & OSError

### ISSUE THREAD

**Issue by GooDeeJaY** [MarshalX/yandex-music-api#235]
**Code**
```
from yandex_music.client import Client
from yandex_music.utils import request
 
Client(request=request.Request(proxy_url="176.103.49.189:1182"))
```

**Error:**
> yandex_music.exceptions.NetworkError: HTTPSConnectionPool(host='api.music.yandex.net', port=443): Max retries exceeded with url: /account/status (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))

I don't know why I'm getting ProxyError, I tested proxy at proxy checker sites and they are showing that it is working well.
Why it is saying too many open connections?

**Comment by MarshalX** [comment]
@GooDeeJaY As I understand it, this is a public proxy server. A lot of people use it, and it has a connection limit. This is not a bug in the library, use your own or private proxy server.

**Comment by MarshalX** [comment]
To check my words, you can manually or cycle create a client many times using this proxy server. As soon as someone else disconnects from him - the request will be successful

**Comment by MarshalX** [comment]
Here is a stand to check:

```python
from yandex_music.client import Client
from yandex_music.utils import request
from yandex_music.exceptions import NetworkError

client = None

while client is None:
    try:
        client = Client(request=request.Request(proxy_url="176.103.49.189:1182"))
    except NetworkError:
        pass

print(client)

```
