### ISSUE TITLE
Метод client.tracks не учитывает содержимого поля version

### ISSUE THREAD

**Issue by IlyaKustov** [MarshalX/yandex-music-api#238]
При запросе https://api.music.yandex.net/tracks/2469815:245214 в содержимом поля version есть информация об особенности трека - **_Radio Edit_**

`{"invocationInfo":{"hostname":"music-stable-back-sas-5.sas.yp-c.yandex.net","req-id":"1582897179209691-9820607299576798752","exec-duration-millis":"0"},"result":[{"id":"2469815","realId":"2469815","title":"Carnival of Rust","version":"Radio Edit","major":{"id":20,"name":"SOYUZ"},"available":true,"availableForPremiumUsers":true,"availableFullWithoutPermission":false,"durationMs":220710,"storageDir":"367125_7225f313.59899311.1.2469815","fileSize":5297632,"normalization":{"gain":-11.17,"peak":32766},"previewDurationMs":30000,"artists":[{"id":226029,"name":"Poets Of The Fall","various":false,"composer":false,"cover":{"type":"from-artist-photos","prefix":"c5677760.p.226029/","uri":"avatars.yandex.net/get-music-content/28589/c5677760.p.226029/%%"},"genres":[]}],"albums":[{"id":245214,"title":"Carnival of Rust","type":"single","year":2006,"releaseDate":"2006-03-22T00:00:00+03:00","coverUri":"avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%","ogImage":"avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%","genre":"rock","buy":[],"trackCount":3,"recent":false,"veryImportant":false,"artists":[{"id":226029,"name":"Poets Of The Fall","various":false,"composer":false,"cover":{"type":"from-artist-photos","prefix":"c5677760.p.226029/","uri":"avatars.yandex.net/get-music-content/28589/c5677760.p.226029/%%"},"genres":[]}],"labels":[{"id":561988,"name":"Студия СОЮЗ"}],"available":true,"availableForPremiumUsers":true,"availableForMobile":true,"availablePartially":false,"bests":[],"trackPosition":{"volume":1,"index":1}}],"coverUri":"avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%","ogImage":"avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%","lyricsAvailable":true,"type":"music","rememberPosition":false}]}`

а вот при вызове метода API 

`client.tracks(['2469815:245214'])`

в ответе поле\поля version пустые

`{'title': 'Carnival of Rust', 'available': True, 'artists': [{'name': 'Poets Of The Fall', 'cover': {'uri': 'avatars.yandex.net/get-music-content/28589/c5677760.p.226029/%%', 'items_uri': None, 'prefix': 'c5677760.p.226029/', 'version': None, 'custom': None, 'error': None, 'type_': 'from-artist-photos', 'dir_': None}, 'various': False, 'composer': False, 'genres': [], 'op_image': None, 'no_pictures_from_search': None, 'counts': None, 'available': None, 'ratings': None, 'links': [], 'tickets_available': None, 'regions': None, 'decomposed': None, 'popular_tracks': [], 'likes_count': None, 'full_names': None, 'description': None, 'countries': None, 'en_wikipedia_link': None, 'db_aliases': None, 'aliases': None, 'init_date': None, 'end_date': None, 'id_': 226029}], 'albums': [{'title': 'Carnival of Rust', 'track_count': 3, 'artists': [{'name': 'Poets Of The Fall', 'cover': {'uri': 'avatars.yandex.net/get-music-content/28589/c5677760.p.226029/%%', 'items_uri': None, 'prefix': 'c5677760.p.226029/', 'version': None, 'custom': None, 'error': None, 'type_': 'from-artist-photos', 'dir_': None}, 'various': False, 'composer': False, 'genres': [], 'op_image': None, 'no_pictures_from_search': None, 'counts': None, 'available': None, 'ratings': None, 'links': [], 'tickets_available': None, 'regions': None, 'decomposed': None, 'popular_tracks': [], 'likes_count': None, 'full_names': None, 'description': None, 'countries': None, 'en_wikipedia_link': None, 'db_aliases': None, 'aliases': None, 'init_date': None, 'end_date': None, 'id_': 226029}], 'labels': [{'name': 'Студия СОЮЗ', 'id_': 561988}], 'available_for_premium_users': True, 'available': True, 'cover_uri': 'avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%', 'genre': 'rock', 'year': 2006, 'release_date': '2006-03-22T00:00:00+03:00', 'bests': [], 'prerolls': None, 'volumes': None, 'og_image': 'avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%', 'buy': [], 'recent': False, 'very_important': False, 'available_for_mobile': True, 'available_partially': False, 'track_position': {'volume': 1, 'index': 1}, 'regions': None, 'original_release_year': None, 'content_warning': None, 'id_': 245214, 'type_': 'single'}], 'available_for_premium_users': True, 'lyrics_available': True, 'real_id': '2469815', 'og_image': 'avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%', 'cover_uri': 'avatars.yandex.net/get-music-content/98892/ea399668.a.245214-2/%%', 'major': {'name': 'SOYUZ', 'id_': 20}, 'duration_ms': 220710, 'storage_dir': '51327_109b74ca.36526310.1.609676', 'file_size': 5297632, 'normalization': {'gain': -11.17, 'peak': 32766}, 'error': None, 'regions': None, 'available_as_rbt': None, 'content_warning': None, 'explicit': None, 'preview_duration_ms': 30000, 'available_full_without_permission': False, 'download_info': None, 'id_': '2469815', 'type_': 'music'}
`

**Comment by MarshalX** [comment]
Спасибо!
