### ISSUE TITLE
Папка с примерами пуста

### ISSUE THREAD

**Issue by fghf333** [MarshalX/yandex-music-api#24]
Папка с примерами, содержит в себе только ReadMe и License. Может стоит туда что-нибудь добавить? Учитывая, что в основном ReadMe рекомендуется смотреть на эти самые примеры.

**Comment by MarshalX** [comment]
Да, конечно же стоит. Создайте ПР, приму

**Comment by MarshalX** [comment]
Примеры добавлены.
