### ISSUE TITLE
Присоеденение к коллективному плейлисту

### ISSUE THREAD

**Issue by glebliutsko** [MarshalX/yandex-music-api#317]
В ЯМ есть можно предоставить совместный доступ по ссылке к плейлисту. Сгенерировать ссылку можно только в Web-версии. Сгенерированная ссылка будет иметь следующий вид: `https://music.yandex.ru/users/{user_id}/playlists/{playlist_id}?token={token}`.

Для принятия соглашения используется следующий эндпоинт
```http
POST /playlists/collective/join?uid={user_id}&token={token}
```
В ответ приходит.
```json
{
    "invocationInfo": {
        "hostname": "music-stable-back-vla-17.vla.yp-c.yandex.net",
        "req-id": "1588706178942769-825958853261467531",
        "exec-duration-millis": "26"
    },
    "result": "ok"
}
```
При этом, плейлисту автоматически ставится отметка "Мне нравится".

**Comment by MarshalX** [comment]
Спасибо!
