### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by gleb34783** [MarshalX/yandex-music-api#334]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'advertisement': 'Оформите постоянную подписку – первый месяц бесплатно!', 'bar_below': {'alert_id': 'xxx', 'text': 'тест Подписка скоро закончится. А вместе с ней закончатся музыка и подкасты без ограничений. Не надо так.', 'bg_color': '#FF5038', 'text_color': '#FFFFFF', 'alert_type': 'Churn_SubscriptionEnd_Music', 'button': {'text': 'Оформить подписку', 'bg_color': '#FFFFFF', 'text_color': '#191919', 'uri': 'https://plus.yandex.ru/?source=music_web_churn_subscriptionend'}, 'close_button': False}}
Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.product.Product'>; kwargs: {'intro_period_duration': 'P1M', 'start_period_duration': 'P1M', 'intro_price': {'amount': 99.0, 'currency': 'RUB'}, 'start_price': {'amount': 99.0, 'currency': 'RUB'}, 'plus': True}
Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'non_auto_renewable_remainder': {'days': 166}}
Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'advertisement': 'Оформите постоянную подписку – первый месяц бесплатно!'}

**Comment by MarshalX** [comment]
Спасибо!
