### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by GEkuL** [MarshalX/yandex-music-api#340]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'advertisement': 'Оформите постоянную подписку – первый месяц бесплатно!', 'bar_below': {'alert_id': 'xxx', 'text': 'тест Подписка скоро закончится. А вместе с ней закончатся музыка и подкасты без ограничений. Не надо так.', 'bg_color': '#FF5038', 'text_color': '#FFFFFF', 'alert_type': 'Churn_SubscriptionEnd_Music', 'button': {'text': 'Оформить подписку', 'bg_color': '#FFFFFF', 'text_color': '#191919', 'uri': 'https://plus.yandex.ru/?source=music_web_churn_subscriptionend'}, 'close_button': False}}


```
Возможно,я уже писал, о этом предпупреждении, и все уже исправлено. После обновления библиотеки, этот warning так никуда и не исчез. Проясните, если я что-то не так делаю

**Comment by MarshalX** [comment]
Спасибо, уже было. Добавлено в ветку development, в master еще нет, следовательно и нет на pypi. Вы можете отключить это предупреждения установив другой уровень логирования (есть в ридми), установить версию библиотеки из другой ветки или дождаться выхода новой версии.
