### ISSUE TITLE
Ошибка в хинте для Client.from_credentials

### ISSUE THREAD

**Issue by lemonpaul** [MarshalX/yandex-music-api#355]
Хинт показывает, что ожидается тип 'Optional[(Captcha) -> str]' для аргумента captcha_callback
Должен быть тип 'Optional[(CaptchaResponse) -> str]'
![Screenshot from 2020-07-19 17-42-58](https://user-images.githubusercontent.com/26084945/87877968-06b0c600-c9ea-11ea-8a98-e733235a1a5a.png)

**Comment by MarshalX** [comment]
@glebliutsko
