### ISSUE TITLE
Нет объектов в поле tracks у users_playlists_list

### ISSUE THREAD

**Issue by Neoniklain** [MarshalX/yandex-music-api#359]
При выполнении client.users_playlists_list() в ответ не приходят трэки плэйлиста, поле traks пустое.

Шаги для воспроизведения бага:
1. Вызвать users_playlists_list()
2. Поле traks пусто

Ожидаемое поведение
В поле трэков будут лежать id трэков, которые принадлежат плэйлисту.

Есть ли альтернативный способ получить список треков в плэйлисте?

**Comment by MarshalX** [comment]
Это не баг библиотеки. Так работает API. Да, есть альтернативные методы для получения плейлиста, но уже с треками. users_playlists_list() Нужен исключительно для отображения плейлистов пользователя, а уже содержимое получается по kind и owner определенного плейлиста через другой метод. В дев ветке был добавлен шорткат для получения плейлиста с треками, в мастере ещё нет.

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api/commit/469cf448f3167aa071fe81da329f0f85c0fb341f

**Comment by Neoniklain** [comment]
Понятно. Спасибо.
