### ISSUE TITLE
Импорт треков в плейлист?

### ISSUE THREAD

**Issue by vtssi** [MarshalX/yandex-music-api#360]
Здравствуйте, у меня есть список треков (10 тысяч штук) такого вида:
http://music.yandex.ru/album/4667862/track/36960287
http://music.yandex.ru/album/7901084/track/54673829
http://music.yandex.ru/album/3741427/track/30917138
...
Как мне их можно импортировать в пустой плейлист?

**Comment by glebliutsko** [comment]
1. Перейти на страницу плейлиста в приложении
2. Нажать `Добавить в Плейлист`
![Screenshot_20200802_144517.jpg](https://user-images.githubusercontent.com/40576167/89122362-90c35900-d4d7-11ea-862e-a913d1e79580.jpg)
3. Выбрать плейлист
![Screenshot_20200802_144532_ru.yandex.music.jpg](https://user-images.githubusercontent.com/40576167/89122367-991b9400-d4d7-11ea-89a2-9f17ddeb314b.jpg)
4. Повторить для остальных плейлистов.

**Comment by MarshalX** [comment]
Использовать методы для создания плейлиста и его изменения. Не знаю обработает ли за раз 10к, никогда такого не проверял. 

Вот этот класс вам поможет подготовить данные для отправки https://github.com/MarshalX/yandex-music-api/blob/development/yandex_music/utils/difference.py

Вот так он используется для одного трека: https://github.com/MarshalX/yandex-music-api/blob/development/yandex_music/client.py#L1121

А вот метод для отправки вашего запроса: https://github.com/MarshalX/yandex-music-api/blob/134f3bcf0d68418dc14904cf165660c0a1d0eaca/yandex_music/client.py#L1079

**Comment by vtssi** [comment]
Спасибо, попробую.
