### ISSUE TITLE
Выдача 30 секундного отрезка

### ISSUE THREAD

**Issue by SmoKE585** [MarshalX/yandex-music-api#361]
Используют модифицированную вашу библиотеку на PHP (Суть то одна и та же) и до недавнего времени все работало, а недавно вместо полного файла Яша начал выдавать куски по 30 секунд. Правильно ли я понимаю, что это связано с введением очередей или нет?

P.S. Был написан модуль для одной из систем умного дома и модулем пользуется достаточно много людей =) Прошу помощи =(
[https://mjdm.ru/forum/viewtopic.php?f=5&t=7103#p119231](https://mjdm.ru/forum/viewtopic.php?f=5&t=7103#p119231)

**Comment by glebliutsko** [comment]
Яндекс ограничил скачивание треков. Теперь, для получения полного трека нужна авторизация.

**Comment by SmoKE585** [comment]
> Яндекс ограничил скачивание треков. Теперь, для получения полного трека нужна авторизация.

Но ведь авторизация проходит, получаю токен, использую его при запросе ссылки + вижу инфо о подписке...
Есть вариант решить?

**Comment by MarshalX** [comment]
> > Яндекс ограничил скачивание треков. Теперь, для получения полного трека нужна авторизация.
> 
> Но ведь авторизация проходит, получаю токен, использую его при запросе ссылки + вижу инфо о подписке...
> Есть вариант решить?

Перепроверьте запрос на получение информации о загрузке. Точно выполняется с токеном? За вашу версию клиента ручаться не могу, но со своей стороны подтверждаю, что наличие авторизации решает вопрос. Даже без подписки.
