### ISSUE TITLE
Добавить возможность задать timeout для клиента

### ISSUE THREAD

**Issue by lemonpaul** [MarshalX/yandex-music-api#362]
Сейчас есть возможно задать timeout для каждого запроса к API, но нет возможности прописать его сразу в клиенте, чтобы не передавать по сто раз. Очень хотелось бы иметь такую возможность.

**Comment by glebliutsko** [comment]
Мне кажется, или этот issue можно закрывать?

**Comment by MarshalX** [comment]
Ну да, но я ещё не смерджил в main. Вот и висит
