### ISSUE TITLE
Исправить ошибку из Best.de_json при поиске подкастов

### ISSUE THREAD

**Issue by nburmistrov** [MarshalX/yandex-music-api#364]
**Опишите проблему**
Есть у меня такой код:
_search_result = y_client.search(search_str)_
Через который я получаю результат поиска и вытаскиваю оттуда треки. В целом, ищу только песни, но тут я решил найти **подкаст** и в результате получил данную ошибку. 

**Воспроизведение**
Шаги для воспроизведения бага:
1. Создать экземпляр объекта yandex_music.Client;
2. Авторизоваться.
3. Вызвать метод метод с любым из данных аргументов:
3.1 y_client.search('Я бы выпил')
3.2 y_client.search('как стать мастером запоминания ted')
3.3 y_client.search('Илья Варламов Подкаст')
4. Получить ошибку

**Ожидаемое поведение**
Получить в результате объект yandex_music.Search с полем best.

**Логи**
![image](https://user-images.githubusercontent.com/45319015/90962155-b1c40c00-e4cf-11ea-89c8-5bd1bc64771d.png)

**Дополнительная информация**
Такая ошибка у меня возникает только с поиском подкастов. Данную ошибку можно обойти, если указать конкретный тип в поиске:
_search_result = y_client.search(search_str, type_='track')_ 
Судя по стектрейсу, Best.de_json не может нормально десериализовать результат и скорее всего, проблема с типами 'podcast' или 'album'.

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api/commit/3f3a742548dbd9d186a4470e726a8e53eaf20a96
