### ISSUE TITLE
[Вопрос] Endpoints для отправки feedback на прослушанный трек

### ISSUE THREAD

**Issue by hankovich** [MarshalX/yandex-music-api#368]
Привет!
В API веб-версии есть методы для отправки фидбека для любого трека (https://music.yandex.ru/api/v2.1/handlers/track/{trackId}/{origin}/feedback/[start, finish, skip]), есть ли что-нибудь такое в API для приложений (не только для радио)?

Охочусь не за реализацией в данной библиотеке, достаточно было бы схемы ендпоинтов.
Спасибо.

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api/blob/410f433f800631ea45e4cded9b9269a32c6e5223/yandex_music/client.py#L693

**Comment by hankovich** [comment]
Спасибо большое!

А я искал по словам feedback/history 🤦‍♂️
