### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by ManlyMan1** [MarshalX/yandex-music-api#373]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
Type: <class 'yandex_music.album.album.Album'>; kwargs: {'storage_dir': '5765b156.a.6040088'}

```

**Comment by arynyklas** [comment]
Решил так:
import logging
yandex_music.base.logger.setLevel(logging.ERROR)
