### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by Arkanium77** [MarshalX/yandex-music-api#376]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:
Выпадают ещё до начала ```Importing liked tracks```. В целом, данные копируются нормально
```
Type: <class 'yandex_music.track.track.Track'>; kwargs: {'is_suitable_for_children': True}
Type: <class 'yandex_music.track.track.Track'>; kwargs: {'background_video_uri': 'https://video-preview.s3.yandex.net/vh/VIDEO_ID.mp4'}

```

**Comment by arynyklas** [comment]
Решил так:
import logging
yandex_music.base.logger.setLevel(logging.ERROR)

**Comment by Arkanium77** [comment]
> Решил так:
> import logging
> yandex_music.base.logger.setLevel(logging.ERROR)

Ну, это не решение, это маскировка проблемы :)
Мне в принципе не мешают сами логи, просто, ну, наверное если есть какие-то неизвестные поля надо их обрабатывать
