### ISSUE TITLE
GPL -> LGPL

### ISSUE THREAD

**Issue by OwnageIsMagic** [MarshalX/yandex-music-api#412]
в коммите 233e730 on Jul 19, 2019 была изменна лицезия с GPL на LGPL, но к этому времени в проект успели вложится другие люди. Для смены лицензии требуется явное согласие всех участников

**Comment by MarshalX** [comment]
@OwnageIsMagic В этом коммите было исправлено отображение лицензии на гитхабе, а не лицензия. Если посмотреть на ридми репозитория, то в последнем абзаце идёт речь про lgpl и предоставляется ссылка на https://www.gnu.org/licenses/lgpl-3.0.html

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api/blob/233e730ad7046a4b08827bd9b559856367d25f8d/README.rst#%D0%BB%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F

**Comment by MarshalX** [comment]
при необходимости следует переоткрыть
