### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by ShevtsovPM** [MarshalX/yandex-music-api#438]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '...тут был хеш, но я его вырезал...'}

**Comment by MarshalX** [comment]
Спасибо, уже есть #434 #421
