### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by Shagivaleev** [MarshalX/yandex-music-api#496]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
import yandex_music

email = 'xxx@yandex.ru'
pswrd = '***'


cl = yandex_music.Client.from_credentials(username=email, password=pswrd)

```
Errors: --------------------------------------------
Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}

Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'masterhub': {'active_subscriptions': [], 'available_subscriptions': []}, 'userhash': '4c6afd61122591a7c1a345d1f4155978bc5dc95749add2ba9287b45e64733631'}

**Comment by MarshalX** [comment]
Спасибо, уже есть
