### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by savegame** [MarshalX/yandex-music-api#502]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': False}
```
и далее
```
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'masterhub': {'active_subscriptions': [], 'available_subscriptions': []}, 'userhash': 'тут цифры и буквы, видимо чуствительная инфа'}
```

P.S. просто решил опробовать ~~ваш скрипт~~ библиотеку на только что созданном аккаунте без подписок.

**Comment by savegame** [comment]
вижу что подобных сообщение тут 100500 штук, свою закрою, отпишусь в каком нидуь из предудущих

**Comment by MarshalX** [comment]
@savegame спасибо ❣️
