### ISSUE TITLE
Feature request : Сделать экранирование названия трека

### ISSUE THREAD

**Issue by json1c** [MarshalX/yandex-music-api#536]
Есть метод `track.download`, который скачивает трек в определенную папку
Если в названии трека есть символ /, то создается еще одна папка. Выглядит это примерно так:

`downloads/ym_100524465:21106180uLZRc/IC3PEAK, Kim Dracula - Червь / Worm.mp3`

Предлагаю сделать экранирование названия трека для таких случаев. Если нужно могу разобраться и кинуть PR.

**Comment by MarshalX** [comment]
Но ведь у `track.download` передается путь включая имя файла. Это нормально что если вы передали в путь `/`, то будет подпапка. То что у трека может оказаться `/` в названии это забота того кто вызывает метод. Потому что библиотека не подставляет имена треков. Это сделал разработчик использующий библиотеки. На нём и ответственность за экранирование.
