### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'tracks'

### ISSUE THREAD

**Issue by KeilWin** [MarshalX/yandex-music-api#579]
**Опишите ошибку**
AttributeError: 'coroutine' object has no attribute 'tracks' в асинхронном клиенте, при вызове метода fetch_tracks_async()

**Воспроизведение**
Шаги для воспроизведения ошибки:
1. Создать объект  ClientAsync, c токеном
2. Вызвать метод playlists_list(f'{owner_id}:{playlist_id}')
3. Вызвать метод к нулевому элементу(плейлист существует) fetch_tracks_async()
4. Получить ошибку

**Ожидаемое поведение**
Получить coroutine.

**Логи**
File "PATH\venv\lib\site-packages\yandex_music\playlist\playlist.py", line 278, in fetch_tracks_async
    return await self.client.users_playlists(self.kind, self.owner.uid, *args, **kwargs).tracks
AttributeError: 'coroutine' object has no attribute 'tracks'

**Дополнительная информация**
Предположительно, потеряны скобки в методе fetch_tracks_async(), из-за чего происходит возврат coroutine, а не списка треков, List['TrackShort'].
Это решило мою проблему
yandex_music\playlist\playlist.py 

ошибка line 278>>>>return await self.client.users_playlists(self.kind, self.owner.uid, *args, **kwargs).tracks
работает line 278>>>>return (await self.client.users_playlists(self.kind, self.owner.uid, *args, **kwargs)).tracks

**Comment by MarshalX** [comment]
Спасибо за подрробный баг реперт и решение проблемы! Это было исправлено в https://github.com/MarshalX/yandex-music-api/commit/83c1ddb6e2c5d1b68303334bc4d14b34e6087cae, но, к сожалению, так и лежит ещё в dev ветке и не было релизнуто. Если вам нужно срочное решение, то установите библиотеку с дев ветки: `pip install git+ssh://git@github.com:MarshalX/yandex-music-api.git@dev`

**Comment by KeilWin** [comment]
> Спасибо за подрробный баг реперт и решение проблемы! Это было исправлено в [83c1ddb](https://github.com/MarshalX/yandex-music-api/commit/83c1ddb6e2c5d1b68303334bc4d14b34e6087cae), но, к сожалению, так и лежит ещё в dev ветке и не было релизнуто. Если вам нужно срочное решение, то установите библиотеку с дев ветки: `pip install git+ssh://git@github.com:MarshalX/yandex-music-api.git@dev`

Понял, спасибо!
