### ISSUE TITLE
Битая ссылка на странице "Пример работы с радио"

### ISSUE THREAD

**Issue by acherkashin** [MarshalX/yandex-music-api#585]
**Опишите ошибку**
Битая ссылка на странице https://github.com/MarshalX/yandex-music-api/tree/main/examples/radio_example

<img width="1366" alt="Screenshot 2023-02-20 at 22 21 46" src="https://user-images.githubusercontent.com/9947582/220177577-e830226d-6ef1-40fd-9ee4-d92d3e14bf46.png">

<img width="851" alt="image" src="https://user-images.githubusercontent.com/9947582/220177648-412b7d95-f96d-4937-96cd-d2272e5e2db1.png">

**Comment by MarshalX** [comment]
Спасибо
