### ISSUE TITLE
Обложка трека говорит об окончании действия приложения 5 мая

### ISSUE THREAD

**Issue by andronix1** [MarshalX/yandex-music-api#590]
Если скачать обложку через download_cover, то скачается такая обложка:
![image](https://user-images.githubusercontent.com/81802236/236251603-ef889c94-aa7d-4347-aa72-3c351eac4d02.png)

**Comment by MarshalX** [comment]
Исправлено. Обновите библиотеку `pip install yandex-music==2.1.1`
