### ISSUE TITLE
Not allowed при получении download info

### ISSUE THREAD

**Issue by andronix1** [MarshalX/yandex-music-api#595]
При получении download info выбрасывается ошибка: `yandex_music.exceptions.UnauthorizedError: {'name': 'not-allowed', 'message': ''} `
Ошибка пропадает, если заменить в заголовках `'X-Yandex-Music-Client': 'YandexMusicAndroid/24023231'` на `'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'`

**Comment by MarshalX** [comment]
@andronix1 а как получали токен для работы с ЯМ?

**Comment by andronix1** [comment]
Через расширение для chrome как в документации

**Comment by glebliutsko** [comment]
> Через расширение для chrome как в документации

Пробовал через такой токен. У меня работало. У вас эту ошибку на всех треков выдает или каком-то определенном. Если последнее, скиньте ссылку, пожалуйста.

**Comment by andronix1** [comment]
@glebliutsko, на всех

**Comment by MarshalX** [comment]
Не смогли воспроизвести
