### ISSUE TITLE
cover_uri содержит устаревшую ссылку на картинку

### ISSUE THREAD

**Issue by EasyLim** [MarshalX/yandex-music-api#617]
**Суть проблемы**
В cover_uri устаревшая ссылка. Сейчас все ссылки, которые можно получить в cover_uri ведут на картинку, содержащую следующий текст: "Скоро эта версия приложения перестанет работать. Удалите старое приложение и установите актуальную версию из Google Play. 18+" 

![300x300](https://github.com/MarshalX/yandex-music-api/assets/49363253/eb19d0f6-72fc-46d7-b57d-d3e92aef3076)

**Воспроизведение**
Python код для воспроизведения ошибки:
```python
from yandex_music import Client

client = Client().init()
search_result = client.search("Hello")
results = search_result.tracks.results
print(f"https://{results[0].cover_uri[:-2]}200x200")
```

**Ожидаемое поведение**
Ссылка на картинку должна соответствовать картинке отображаемой в Yandex Music при поиске или при проигрывании трека.

**Примечание**
Последний раз, когда проверял работу ссылок, было начало сентября. Проблему обнаружил только сейчас.

**Comment by MarshalX** [comment]
@glebliutsko привет, можешь глянуть актуальный заголовок на Android?
