### ISSUE TITLE
Возможность проверить наличие трека в других регионах

### ISSUE THREAD

**Issue by wileyfoxyx** [MarshalX/yandex-music-api#621]
Возможное наличие данной функции обосновывается тем, что Я.Музыка доступна не только в России (в частности, в странах СНГ а также в Израиле под брендом [Yango Music](https://music.yango.com)), и какие-то треки доступные в других регионах могут быть недоступны в РФ и наоборот.

Яркий пример - любой релиз, выпущенный лейблом Sony Music Entertainment (и их дочерними лейблами, региональными отделениями и т.д.). Все релизы, выпущенные лейблом, были скрыты из российского каталога Я.Музыки, но еще доступны в других регионах, или если пользователь добавил песню до ее скрытия (конкретно, до сентября 2022, когда SME [объявила](https://www.rbc.ru/life/news/631a16a09a79473c579237fe) об окончательном уходе с российского рынка), или обходными путями (лайкнув видеоклип или используя функцию [импорта музыки](https://music.yandex.ru/newimport)).

**Comment by MarshalX** [comment]
Разве при запросе трека нет полей перечисляющий код регионов в которых доступен трек? Например в https://yandex-music.readthedocs.io/en/main/yandex_music.track.track.html#yandex_music.track.track.Track.regions

**Comment by llimonix** [comment]
> Разве при запросе трека нет полей перечисляющий код регионов в которых доступен трек? Например в https://yandex-music.readthedocs.io/en/main/yandex_music.track.track.html#yandex_music.track.track.Track.regions

как я последний раз видел, там выдает None

**Comment by wileyfoxyx** [comment]
> как я последний раз видел, там выдает None

подтверждаю, у меня тоже выдает None

**Comment by MarshalX** [comment]
Боюсь это неправильное место для запроса подобных фич. Будет эндпоинт – можно будет добавить в библиотеку. Эндпоинты добавляет Яндекс. Стоит просить их
