### ISSUE TITLE
При получении полных версий треков конкретного плейлиста поле tracks содержит пустой список

### ISSUE THREAD

**Issue by v9lu** [MarshalX/yandex-music-api#630]
**Опишите ошибку**
При получении полных версий треков плейлиста https://music.yandex.ru/users/music-blog/playlists/2000 - полные версии треков отсутствуют.

**Воспроизведение**
```
yandex_client = Client().init()
full_tracks = yandex_client.users_playlists(kind=2000, user_id="music-blog").tracks
```

**Ожидаемое поведение**
Поле track в каждом треке из списка full_tracks должно содержать полную информацию о треке (заместо этого содержит None)

**Comment by MarshalX** [comment]
Плейлист всегда возвращал краткую версию треков. Запрашивать полные версии нужно отдельным запросом. Делается это так:
```python
playlist = yandex_client.users_playlists(kind=2000, user_id='music-blog')
full_tracks = yandex_client.tracks([track.track_id for track in playlist.tracks])
print(full_tracks)
```
