### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by ValeriGolovin** [MarshalX/yandex-music-api#637]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
Type: <class 'yandex_music.account.alert.Alert'>; kwargs: {'close_button_styles': {}}
Traceback (most recent call last):
  File "c:/Users/Asus/Desktop/Kesha/yandexmusic1.py", line 11, in <module>
    client.login(username, password)
AttributeError: 'Client' object has no attribute 'login'

```

**Comment by MarshalX** [comment]
https://github.com/MarshalX/yandex-music-api#%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF-%D0%BA-%D0%B2%D0%B0%D1%88%D0%B8%D0%BC-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC-%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0
