### ISSUE TITLE
Убрать обьект клиента или сделать опциональным в методах десериализации

### ISSUE THREAD

**Issue by nyashkin** [MarshalX/yandex-music-api#643]
Сначала вызвало недопонимание наличие инстанса клиента как обязательного аргумента в методе десериализации . Зачем? Пришлось прокидывать в хендлер в котором есть метод десериализации инстанс клиента. Потом залез в код и увидел это:

` if client.report_unknown_fields and unknown_data:
            cls.report_unknown_fields_callback(cls, unknown_data)`

Это единственные две строки где используется клиент. Зачем? Чтобы импортировать одну настройку из клиента. Сделайте это опциональным, писать лишний код из-за ненужного функционала это вовсе не правильно.

**Comment by MarshalX** [comment]
это нужно для методов сокращений
