### ISSUE TITLE
Чат бот Telegram удален

### ISSUE THREAD

**Issue by MortemSineNobis** [MarshalX/yandex-music-api#647]
Удалено по требованию BrandMonitor. ООО «Бренд Монитор» является уполномоченным представителем компании ООО «Яндекс»

  При попытке активации бота получаю следующее сообщение:
      
    Удалено по требованию BrandMonitor. ООО «Бренд Монитор» является уполномоченным представителем компании ООО «Яндекс»
      
      ✅ Вы успешно авторизовались
      
      Перейдите к любому из ботов от сообщества:
      - @Tilekk_bot
      - @PeretsGG_bot
      - @MusicSoundBot
      - @Swuoltg_bot
      - @LokitaBot

**Comment by MarshalX** [comment]
Причем тут библиотека?

**Comment by MortemSineNobis** [comment]
Ссылка в документации ведет на чатбот. Стоить удалить его упоминание

**Comment by MarshalX** [comment]
Где конкретно? Если в **соседнем** проекте по получению токена, то там нужно нажимать "скопировать токен". В боте ничего не надо

**Comment by MortemSineNobis** [comment]
Согласен, моя ошибка. Вчера не заметил кнопку.
