### ISSUE TITLE
emtpy queue

### ISSUE THREAD

**Issue by ternyavsky** [MarshalX/yandex-music-api#652]
**Опишите ошибку**
Empty queue tracks, but track played, or i durachek

![yamusic](https://github.com/user-attachments/assets/b544259e-8f56-4026-a245-e895b4189ac9)

**Comment by MarshalX** [comment]
Очереди остались поддерживаться в ЯМ приложении под Windows. Веб версия должно быть уже использует новый подход на вебсокетах

**Comment by ternyavsky** [comment]
Есть выход какой-то? мб device arg что-то решает?

**Comment by MarshalX** [comment]
Выход: использовать клиент названный выше для прослушивания музыки
