### ISSUE TITLE
queues list index out of range

### ISSUE THREAD

**Issue by abrikos2** [MarshalX/yandex-music-api#654]
Попытался вставить код из примера "Текст текущего играющего трека" а получил что список играющих треком пустой 
`Traceback (most recent call last):
  File "c:\Users\danya\Desktop\Python\Igor.py", line 13, in <module>
    last_queue = client.queue(queues[0].id)
                              ~~~~~~^^^
IndexError: list index out of range`

**Comment by MarshalX** [comment]
Дубликат https://github.com/MarshalX/yandex-music-api/issues/652
