### ISSUE TITLE
Библиотека несовместима с Python 3.6

### ISSUE THREAD

**Issue by crinny** [MarshalX/yandex-music-api#7]
Если пытаться запустить пример из ридми, используя Python 3.6, появится следующая ошибка:
```
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```
Связано это с тем, что `fromisoformat` появился только в версии 3.7. Прошу исправить это, или изменить версию питона в ридми

**Comment by MarshalX** [comment]
Большое спасибо! Пойду по лёгкой дорожке ибо в своё время намучился с их форматом представления даты и времени.
