### ISSUE TITLE
Задокументировать класс Artist

### ISSUE THREAD

**Issue by MarshalX** [MarshalX/yandex-music-api#91]
Необходимо полностью задокументировать класс [Artist](https://github.com/MarshalX/yandex-music-api/tree/master/yandex_music/artist/artist.py). Пример правильно задокументированного класса: [cover.py](https://github.com/MarshalX/yandex-music-api/blob/master/yandex_music/cover.py). Спасибо за Ваш вклад!

**Comment by Angel777d** [comment]
Взялся
